/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as PerfilRouteImport } from './routes/perfil'
import { Route as BuscarRouteImport } from './routes/buscar'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SerieIdRouteImport } from './routes/serie.$id'
import { Route as FilmeIdRouteImport } from './routes/filme.$id'

const PerfilRoute = PerfilRouteImport.update({
  id: '/perfil',
  path: '/perfil',
  getParentRoute: () => rootRouteImport,
} as any)
const BuscarRoute = BuscarRouteImport.update({
  id: '/buscar',
  path: '/buscar',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SerieIdRoute = SerieIdRouteImport.update({
  id: '/serie/$id',
  path: '/serie/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const FilmeIdRoute = FilmeIdRouteImport.update({
  id: '/filme/$id',
  path: '/filme/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/buscar': typeof BuscarRoute
  '/perfil': typeof PerfilRoute
  '/filme/$id': typeof FilmeIdRoute
  '/serie/$id': typeof SerieIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/buscar': typeof BuscarRoute
  '/perfil': typeof PerfilRoute
  '/filme/$id': typeof FilmeIdRoute
  '/serie/$id': typeof SerieIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/buscar': typeof BuscarRoute
  '/perfil': typeof PerfilRoute
  '/filme/$id': typeof FilmeIdRoute
  '/serie/$id': typeof SerieIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/auth' | '/buscar' | '/perfil' | '/filme/$id' | '/serie/$id'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/auth' | '/buscar' | '/perfil' | '/filme/$id' | '/serie/$id'
  id:
    | '__root__'
    | '/'
    | '/auth'
    | '/buscar'
    | '/perfil'
    | '/filme/$id'
    | '/serie/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthRoute: typeof AuthRoute
  BuscarRoute: typeof BuscarRoute
  PerfilRoute: typeof PerfilRoute
  FilmeIdRoute: typeof FilmeIdRoute
  SerieIdRoute: typeof SerieIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/perfil': {
      id: '/perfil'
      path: '/perfil'
      fullPath: '/perfil'
      preLoaderRoute: typeof PerfilRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/buscar': {
      id: '/buscar'
      path: '/buscar'
      fullPath: '/buscar'
      preLoaderRoute: typeof BuscarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/serie/$id': {
      id: '/serie/$id'
      path: '/serie/$id'
      fullPath: '/serie/$id'
      preLoaderRoute: typeof SerieIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/filme/$id': {
      id: '/filme/$id'
      path: '/filme/$id'
      fullPath: '/filme/$id'
      preLoaderRoute: typeof FilmeIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthRoute: AuthRoute,
  BuscarRoute: BuscarRoute,
  PerfilRoute: PerfilRoute,
  FilmeIdRoute: FilmeIdRoute,
  SerieIdRoute: SerieIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
